;; eglot 是 emacs 中的轻量级 LSP Client, 需要配合 LSP 服务器使用
;; eglot 28版本之后就内置了，用 LSP 需要 compile_command.json 依赖工程生成
;; (require 'eglot)
;; (add-to-list 'eglot-server-programs '((c-mode c++-mode) "clangd"))
;; (add-hook 'c-mode-hook #'eglot-ensure)
;; (add-hook 'c++-mode-hook #'eglot-ensure)
;; (add-hook 'c-ts-mode-hook #'eglot-ensure)
;; (add-hook 'c++-ts-mode-hook #'eglot-ensure)

(use-package treesit-auto
  :demand t
  :init
  (progn
    (setq treesit-font-lock-level 4) ;; 设置高亮层级，4是最高级别
   )
  :config
  ;;(treesit-auto-add-to-auto-mode-alist 'all)
  (global-treesit-auto-mode t)
  :custom
  (treesit-auto-install 'prompt)
  )
(setq major-mode-remap-alist '((c-mode . c-ts-mode)
				       (python-mode . python-ts-mode)
				       (json-mode . json-ts-mode)
				       (yaml-mode . yaml-ts-mode)
				       (bash-mode . bash-ts-mode)))

(use-package citre
  :defer t
  :init
  ;; This is needed in `:init' block for lazy load to work.
  (require 'citre-config)
  ;; Bind your frequently used commands.  Alternatively, you can define them
  ;; in `citre-mode-map' so you can only use them when `citre-mode' is enabled.
  (global-set-key (kbd "C-x c j") 'citre-jump)
  (global-set-key (kbd "C-x c J") 'citre-jump-back)
  (global-set-key (kbd "C-x c p") 'citre-ace-peek)
  (global-set-key (kbd "C-x c u") 'citre-update-this-tags-file)
  :config
  (setq
   ;; Set these if readtags/ctags is not in your PATH.
   citre-readtags-program "/usr/local/bin/readtags"
   citre-ctags-program "/usr/local/bin/ctags"

   ;; Set these if gtags/global is not in your PATH (and you want to use the
   ;; global backend)
   ;; citre-gtags-program "/path/to/gtags"
   ;; citre-global-program "/path/to/global"

   ;; Set this if you use project management plugin like projectile.  It's
   ;; used for things like displaying paths relatively, see its docstring.
   ;; citre-project-root-function #'projectile-project-root

   ;; Set this if you want to always use one location to create a tags file.
   ;; citre-default-create-tags-file-location 'global-cache

   ;; Set this if you'd like to use ctags options generated by Citre
   ;; directly, rather than further editing them.
   citre-edit-ctags-options-manually nil

   ;; If you only want the auto enabling citre-mode behavior to work for
   ;; certain modes (like `prog-mode'), set it like this.
   ;; citre-auto-enable-citre-mode-modes '(prog-mode)
   ))

;; lisp 语义高亮
(use-package lisp-semantic-hl
  :ensure t
  :hook ((emacs-lisp-mode lisp-mode) . lisp-semantic-hl-mode))


(provide 'init-programming)
